version: '3.1'

services:
  nginx:
    image: rhrarodrigo/desafio-fullcycle-docker-nginx:latest
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - node
    networks:
      - default-network
  
  node:
    image: rhrarodrigo/desafio-fullcycle-docker-node:latest
    container_name: node
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default-network

  db:
    image: rhrarodrigo/desafio-fullcycle-docker-mysql:latest
    container_name: db
    restart: always
    networks:
      - default-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
networks:
  default-network:
    driver: bridge